plugins:
    eslint:
        enabled: true
        channel: 'eslint-5'
    config:
        config: .eslintrc.json
exclude_patterns:
    - 'tests/'
    - 'tests-dist/'
    - 'spec/'
    - 'node_modules/'
    - 'site/'
