title: NativeModels
email: william@prefinem.com
description: >-
  NativeModels - Runtime type checking for Javascript
baseurl: /
url: https://nativemodels.js.org
github_username: Prefinem

markdown: kramdown

remote_theme: pmarsceill/just-the-docs
theme: 'just-the-docs'

aux_links:
  'NativeModels on GitHub':
    - 'https://github.com/Prefinem/nativemodels'
